[package]
name = "myrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1.2"
keyboard_query = "0.1.0"
mouce = "0.2.43"
rdev = "0.5.3"
time = "0.3.23"




